name: Publish to PyPI

on:
  workflow_dispatch: 
    inputs:
      version:
        description: "Package version to publish"
        required: true
        default: "0.1.1"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Update version
        run: |
          sed -i "s/^    version=.*/    version='${{ github.event.inputs.version }}',/" setup.py
      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
